version: '3.7'
services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - flask-app
